### ISSUE TITLE
Building old conda environments

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/GaitAnalysisToolKit#150]
In 2018 this env.yml file worked:

```yaml
name: gaitanalysis-dev-oldest
channels:
  - defaults
dependencies:
  - python =2.7.*
  - numpy =1.8.2
  - scipy =0.13.3
  - matplotlib =1.3.1
  - pytables =3.1.1
  - pandas =0.13.1
  - pyyaml =3.10
  - nose =1.3.1
  - sphinx =1.2.2
  - coverage
  - mock =1.0.1
  - numpydoc =0.4
  - pip:
    - dynamicisttoolkit==0.4.0
    - oct2py==2.4.2
 ```

But apparently the "free" channel was moved from "defaults", so this is now required:

```yaml
name: gaitanalysis-dev-oldest
channels:
  - free
  - defaults
dependencies:
  - python =2.7.*
  - numpy =1.8.2
  - scipy =0.13.3
  - matplotlib =1.3.1
  - pytables =3.1.1
  - pandas =0.13.1
  - pyyaml =3.10
  - nose =1.3.1
  - sphinx =1.2.2
  - coverage
  - mock =1.0.1
  - numpydoc =0.4
  - pip:
    - dynamicisttoolkit==0.4.0
    - oct2py==2.4.2
```

conda will resolve the packages in this updated version.

**Comment by moorepants** [comment]
Learned that pixi has a "lowest" setting https://www.youtube.com/watch?v=-69br52PyQ4 which will set all packages to the lowest possible value. This is what has long been needed to run an old environment that is not fully strictly pinned. It prevents transitive dependencies from having the highest value (and possibly breaking code).

**Comment by moorepants** [comment]
I played with pixi a bit. I tried doing the lowest strategy with Python 2.7 + the two pypi deps, but pixi kept throwing an error about the pypi deps (dtk and oct2py). I then tried with Python 3.7 as lowest and got things to work with this `pixi.toml` file:

```toml
[workspace]
name = "gaitanalysis-dev-lowest"
channels = ["conda-forge"]
platforms = ["linux-64"]
solve-strategy = "lowest"

[dependencies]
dynamicisttoolkit = ">=0.4.0"
matplotlib = ">=1.3.1"
numpy = ">=1.8.2"
oct2py = ">=2.4.2,<5.0"
pandas = ">=0.13.1,<=0.24.0"
pytables = ">=3.1.1"
python = ">=3.7"
pyyaml = ">=3.10"
scipy = ">=0.13.3"
# dev
coverage = "*"
mock = ">=1.0.1"
nose = ">=1.3.1"
numpydoc = "<1.6"
sphinx = ">=1.2.2"
# numpy and pandas fail to import without these:
gcc = "*"
libgcc = "*"
```

I had to add gcc for this error when import numpy:

```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/core/../../../.././libgomp.so.1: version `GOMP_4.0' not found (required by /home/user/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/numpy/linalg/../../../../liblapack.so.3)
```

and libgcc for this error when importing pandas:

```
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/series.py", line 3981, in <module>
    Series._add_series_or_dataframe_operations()
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/generic.py", line 8899, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  File "/home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/core/window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: /home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/_libs/../../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/moorepants/src/pixi/GaitAnalysisToolKit/.pixi/envs/default/lib/python3.7/site-packages/pandas/_libs/window.cpython-37m-x86_64-linux-gnu.so)
```

With those two additional packages, it seems to install a lowest set.

**Comment by moorepants** [comment]
You have to `pixi install` or `pixi reinstall` alongside the toml file. This creates a `.pixi` folder in the directory with the environment.

**Comment by moorepants** [comment]
Actually I seem to be hitting the pandas import error with a new install (not sure why it worked earlier).

Relevant: https://discuss.pytorch.org/t/importerror-lib64-libstdc-so-6-version-glibcxx-3-4-21-not-found/112019/8

**Comment by moorepants** [comment]
Some tips: https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin

**Comment by moorepants** [comment]
Adding `libstdcxx = "*"` seemed to fix the pandas import error.
